CREATE SEQUENCE SEQ_LOGRADOUROS
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Criando a tabela de logradouros
CREATE TABLE TBL_LOGRADOUROS (
    COD_ID INT PRIMARY KEY,
    NOM_NOME VARCHAR(100),
    TXT_CIDADE VARCHAR(100),
    TXT_ESTADO VARCHAR(2),
    TXT_CEP VARCHAR(8)
);


CREATE SEQUENCE SEQ_RESIDENCIAS
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Criando a tabela de residências
CREATE TABLE TBL_RESIDENCIAS (
    COD_ID INT PRIMARY KEY,
    COD_LOGRADOURO_ID INT,
    DAT_DATA_ULTIMA_COLETA DATE,
    IND_CAPACIDADE INT,
    FOREIGN KEY (COD_LOGRADOURO_ID) REFERENCES TBL_LOGRADOUROS(COD_ID)
);


CREATE SEQUENCE SEQ_RESIDENCIAS_PARA_COLETAR_LIXO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Criando a tabela de residências para coletar lixo
CREATE TABLE TBL_RESIDENCIAS_PARA_COLETAR_LIXO (
    COD_ID INT PRIMARY KEY,
    COD_RESIDENCIA_ID INT,
    DAT_HORA TIMESTAMP,
    FOREIGN KEY (COD_RESIDENCIA_ID) REFERENCES TBL_RESIDENCIAS(COD_ID)
);


CREATE SEQUENCE SEQ_COLETA
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Criando a tabela de coleta
CREATE TABLE TBL_COLETA (
    COD_ID INT PRIMARY KEY,
    DAT_DATA_COLETA TIMESTAMP,
    TXT_TIPO_RESIDUO VARCHAR(50),
    IDN_CONCLUIDA NUMBER(1)
);


CREATE SEQUENCE SEQ_COLETA_LOGRADOUROS
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Criando a tabela de coleta por logradouros
CREATE TABLE TBL_COLETA_LOGRADOUROS (
    COD_COLETA_ID INT,
    COD_LOGRADOURO_ID INT,
    FOREIGN KEY (COD_COLETA_ID) REFERENCES TBL_COLETA(COD_ID),
    FOREIGN KEY (COD_LOGRADOURO_ID) REFERENCES TBL_LOGRADOUROS(COD_ID)
);